server:
  port: 8081
spring:
  application:
    name: discussions
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    listener:
      direct:
        acknowledge-mode=manual:
  #    queues:
  #      name: advertisement
  #      durable: true
  #      exclusive: false
  #      auto-delete: false
  datasource:
    url: jdbc:postgresql://localhost:1978/microDiscussions
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/